apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-logs-pv
  labels:
    app: basicservice
    release: {{ .Release.Name }}
spec:
  capacity:
    storage: {{ .Values.persistence.storageSize }}
  accessModes:
    - ReadWriteOnce
  # storageClassName vacío para binding manual con el PVC
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
  # hostPath apunta al directorio de logs en el nodo Minikube
  hostPath:
    path: {{ .Values.persistence.hostPath | quote }}
    type: DirectoryOrCreate
